services:
  # Backend Service
  - type: web
    name: beaconai-backend
    env: docker
    dockerfilePath: ./deployment/Dockerfile.simple
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: LLM_PROVIDER
        value: auto
      - key: LLM_MODEL
        value: mistralai/Mistral-7B-Instruct-v0.3
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        value: beaconai.ai
      - key: MAILGUN_BASE_URL
        value: https://api.mailgun.net/v3
      - key: SENDER_EMAIL
        value: dale@beaconai.ai
      - key: SENDER_NAME
        value: Dale - BeaconAI Team
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS_FILE
        value: config/google_sheets_credentials.json
      - key: DOCKER_ENV
        value: true
      - key: PORT
        value: 8000

  # Frontend Service (Optional - can be deployed separately)
  - type: web
    name: beaconai-frontend
    env: docker
    dockerfilePath: ./deployment/Dockerfile.frontend
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /_stcore/health
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: beaconai-backend
          property: host
      - key: PORT
        value: 8501